config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get "dashboard/show"

  resources :people
  resources :conversations
  resources :users
  resources :companies

  root "welcome#index"

  get "/quote" => "quotes#show"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :conversations
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user
  belongs_to :person
  belongs_to :company
  validates :user_id, presence: true
  validates :person_id, presence: true
  validates :company_id, presence: true
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :phone_numbers
  has_many :emails
  has_many :addresses
  has_many :conversations
  belongs_to :company
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :person
end

app/models/quote.rb
class Quote < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :conversations

  def salesperson?
    role == "salesperson"
  end

  def manager?
    role == "manager"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @page = params[:page].to_i
    per_page = 5
    @companies = Company.page(@page).per(per_page)
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params["id"])
  end

  def update
    @company = Company.find(params["id"])

    if @company.update(company_params)
      redirect_to companies_path
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params["id"])
    @company.destroy
    redirect_to companies_path
  end

  private def company_params
    params.require("company").permit(:name, :distributor)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def new
    @convo = Conversation.new
    @companies = Company.all
  end

  def show
    @convo = Conversation.find(params["id"])
  end

  def index
    @page = params[:page].to_i
    per_page = 15
    @convos = Conversation.page(@page).per(per_page)
  end

  def create
    @convo = Conversation.new(conversation_params)
    @convo.user = current_user

    if @convo.save
      redirect_to conversations_path
    else
      render :new
    end
  end

  def update
    @convo = Conversation.find(params["id"])

    if @convo.update(conversation_params)
      redirect_to conversations_path
    else
      render :edit
    end
  end

  def edit
    @convo = Conversation.find(params["id"])
    @person_name = Person.find(@convo.person_id).name
  end

  def destroy
    @convo = Conversation.find(params["id"])
    @convo.destroy
    redirect_to conversations_path
  end

  private def conversation_params
    params.require("conversation").permit(:user_id, :person_id, :company_id, :notes, :medium, :follow_up_on)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    begin
      @sales_name = current_user.name
    rescue
      @sales_name = "Erik"
    end
    @follow_ups = Conversation.where(follow_up_on: Date.today)
    @quote = Quote.offset(rand(Quote.count)).first
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @page = params[:page].to_i
    per_page = 5
    @people = Person.page(@page).per(per_page)
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person.id)
    else
      render :new
    end
  end

  def update
    @person = Person.find(params[:id])
    if
      @person.update(person_params)
      redirect_to people_path
    else
      render 'edit'
    end
  end

  def destroy
    @people = Person.find(params[:id])
    @people.destroy

    redirect_to people_path
  end



  private
  def person_params
    params.require(:person).permit(:full_name, :company_id, :comments)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def create
  end

  def index
    @users = User.all
  end

  def update
    User.find(params[:id]).update(role: "manager")
    redirect_to users_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/edit.html.erb
<h1>Edit a company</h1>
<%= form_for @company, url: company_path(id: @company.id), method: :patch do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label "Distributor?" %>
  <%= f.select :distributor, ["true", "false"] %>
  <%= f.submit "Save" %>

<% end %>

app/views/companies/index.html.erb
<table class="table">
  <h2>Companies</h2>

    <th>Name</th>
    <th>Distributor</th>
    <th></th>
    <th></th>
  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td>  <%= company.name %> </td>
      <td>  <% if company.distributor %>
        <i class="fa fa-check" aria-hidden="true"></i>
        <% end %>
      </td>
      <td><%= link_to "Edit", edit_company_path(company.id) %></td>
      <td><%= link_to company_path(company.id), method: :delete, class: "delete" do %>
       <%= fa_icon("trash-o") %> <span>delete</span>
       <% end %>
    </td>
    </tr>
    <% end %>
    <tr></tr>

  </tbody>

</table>

<%= button_to "Add Company", new_company_path, method: :get, class: "btn btn-primary" %>

<%=  paginate @companies %>

app/views/companies/new.html.erb
<h1>Add a company</h1>
<%= form_for @company, url: companies_create_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label "Distributor?" %>
  <%= f.select :distributor, ["true, false"] %>
  <%= f.submit "Save" %>

<% end %>

app/views/conversations/edit.html.erb
<h4>Make changes to this conversation with <%= @person_name %></h4>

<%= form_for @convo, url: conversation_path, method: :patch do |f| %>
  <%= f.label :medium %>
  <%= f.text_field :medium %>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <%= f.label :follow_up_on %>
  <%= f.date_field :follow_up_on %>

  <%= f.submit "Update" %>
  <!-- comment -->

<% end %>

app/views/conversations/index.html.erb
<%=  paginate @convos %>

<% @convos.each do |convo| %>
<p>
  <%= convo.user.name.capitalize %> |
  <%= link_to "View Conversation", conversation_path(convo) %>
</p>
<% end %>

<%= link_to "Add Conversation", new_conversation_path %>

app/views/conversations/new.html.erb
<h4>Record a conversation</h4>

<%= bootstrap_form_for @convo, url: conversations_path, layout: :horizontal do |f| %>
  <%= f.text_field :medium, control_col: 'col-sm-3' %>

  <%= f.date_field :follow_up_on, control_col: 'col-sm-3', value: Time.now.to_date.tomorrow %>

  <%= f.text_field :company, control_col: 'col-sm-3' %>

  <%= f.text_area :notes, control_col: 'col-sm-10' %>

  <%= f.submit "Save Conversation", class: 'btn btn-primary' %>

<% end %>

app/views/conversations/show.html.erb
<dl>
  <dt>Notes:</dt>
  <dd> | <%= @convo.notes %></dd>
</dl>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<table class="table">
 <h2>People</h2>

   <th>Name</th>
   <th>Title</th>
   <th></th>
   <th></th>
 <tbody>
   <% @people.each do |person| %>
   <tr>
     <td>  <%= person.full_name %> </td>

     <td><%= link_to "Edit", edit_person_path(person.id) %></td>
     <td><%= link_to company_path(company.id), method: :delete, class: "delete" do %>
      <%= fa_icon("trash-o") %> <span>delete</span>
      <% end %>
   </td>
   </tr>
   <% end %>
   <tr></tr>

 </tbody>

</table>

<%= button_to "Add Person", new_person_path, method: :get, class: "btn btn-primary" %>

<%= paginate @people %>

app/views/people/new.html.erb
<h1>Add a person</h1>

<%= form_for @person, url: people_path do |f| %>
  <%= f.label :full_name %>
  <%= f.text_field :full_name %>
  <%= f.submit "Save" %>

  <% end  %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>

app/views/users/index.html.erb
<%  @users.each do |user|   %>
<p><%=  user.name   %>
  <%=   user.email  %>
  <%=    user.role   %>
  <%=  link_to  'Update to Manager',  user_path(user.id), :method  => :put  %>
</p>
<%  end %>