config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get "dashboard/show"

  resources :people
  resources :conversations
  resources :users
  resources :companies

  root "welcome#index"

  get "/quote" => "quotes#show"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :conversations
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user
  belongs_to :person
  belongs_to :company
  validates :user_id, presence: true
  validates :person_id, presence: true
  validates :company_id, presence: true
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :phone_numbers
  has_many :emails
  has_many :addresses
  has_many :conversations
  belongs_to :company
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :person
end

app/models/quote.rb
class Quote < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :conversations

  def salesperson?
    role == "salesperson"
  end

  def manager?
    role == "manager"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @page = params[:page].to_i
    per_page = 5
    @companies = Company.page(@page).per(per_page)
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params["id"])
  end

  def update
    @company = Company.find(params["id"])

    if @company.update(company_params)
      redirect_to companies_path
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params["id"])
    @company.destroy
    redirect_to companies_path
  end

  private def company_params
    params.require("company").permit(:name, :distributor)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @page = params[:page].to_i
    per_page = 5
    @people = Person.page(@page).per(per_page)
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person.id)
    else
      render :new
    end
  end

  def update
    @person = Person.find(params[:id])
    if
      @person.update(person_params)
      redirect_to people_path
    else
      render 'edit'
    end
  end

  def destroy
    @people = Person.find(params[:id])
    @people.destroy

    redirect_to people_path
  end



  private
  def person_params
    params.require(:person).permit(:full_name, :company_id, :comments)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def create
  end

  def index
    @users = User.all
  end

  def update
    User.find(params[:id]).update(role: "manager")
    redirect_to users_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PinkPig" %></title>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <script>
      $(document).ready(function() {
        $("#change_background_1").on("click", function(){
          $("body").css("background-color", '#663399');
        });
        $("#change_background_2").on("click", function(){
          $("body").css("background-color", '#CFD8DC');
        });
        $("#change_background_3").on("click", function(){
          $("body").css("background-color", '#BDBDBD');
        });
      });
    </script>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="http://localhost:3000/">PinkPig</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to "Dashboard", dashboard_show_path %></li>
                <p class="navbar-text">

                  Signed in as <%= link_to current_user.email, edit_user_registration_path %></p>

                <li>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                </li>
            <% else %>
                <li>
                  <%= link_to "Sign In", new_user_session_path %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h4>Hop to</h4>
            <ul class="nav nav-list">
              <li><%= link_to "Companies", companies_path %></li>
              <li><%= link_to "Conversations", "/conversations"  %></li>
              <li><%= link_to "People", "/people"  %></li>
              <li><%= link_to "Edit Users", users_path %></li>
              <li>
                <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type "button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Change Color
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><a id="change_background_1">Rebecca Purple</a></li>
                    <li><a id="change_background_2">Blue</a></li>
                    <li><a id="change_background_3">Gray</a></li>
                  </ul>
                </div>
              </li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; MagicalFarms2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>